### ISSUE TITLE
Tidy code tasks metaissue

### ISSUE THREAD

**Issue by crisdosaygo** [dosyago-corp/projectant#14]
- [x] Organize CSS assets across various views, including guest, and have a neat file & directory structure for these.
- [x] organize css for mapper.html
- [x] Remove unnecessary code from changes, particularly related to JS code no longer needed for UI updates.
- [x] restructure code so that simple HTML ( iframes & targeted forms ) only UI with JS for cross context communication 
(  webview <-> webview, iframe <-> webview, iframe, webview <-> main window page, main window page, iframe, webview <-> main process )

**Comment by crisdosaygo** [comment]
Closing as each point done to a level of some satisfaction, and a full and comprehensive treatment of this is not required at this time
